language: python

python:
  - 3.6
  - 3.7

matrix:
  include:
    - os: linux

bundler_args:
  - --retry 2

install:
  - travis_retry pip install -U pytest
  - travis_retry make install-dev

script:
  - travis_retry make test
